### PR TITLE
m_f_j: more useful mail subjects

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Per https://github.com/systemd-cron/systemd-cron/issues/120#issuecomment-1712528145:

```
   1     01:00 systemd-cron    (  14) [tarta] /etc/crontab line 22: failure
   2     00:51 systemd-cron    (4.2K) [tarta] /etc/cron.weekly/dnsmasq-update-adblock-hosts: output
   3   + 00:51 systemd-cron    (2.7K) [tarta] nabijaczleweli's crontab line 2: output
```
(.daily &c. jobs don't have a line number, naturally, crontab ones get one. users' crontabs are pre-parsed as "<file's basename>'s crontab" instead, since the path is horrific)

with
```
Date: Sun, 10 Sep 2023 01:00:00 +0200
From: systemd-cron <root@tarta.nabijaczleweli.xyz>
To: root@tarta.nabijaczleweli.xyz
Subject: [tarta] /etc/crontab line 22: failed
X-Mailer: systemd-cron 2.1.1+testupa-1

× cron-crontab-root-0.service - [Cron] "0 *     * * *   root    echo dupaninka; false"
     Loaded: loaded (/etc/crontab; generated)
     Active: failed (Result: exit-code) since Sun 2023-09-10 01:00:00 CEST; 48ms ago
TriggeredBy: ● cron-crontab-root-0.timer
       Docs: man:systemd-crontab-generator(8)
    Process: 1743692 ExecStart=/bin/sh /run/systemd/generator/cron-crontab-root-0.sh (code=exited, status=1/FAILURE)
   Main PID: 1743692 (code=exited, status=1/FAILURE)
        CPU: 3ms
2023-09-10T01:00:00+0200 tarta systemd[1]: Starting cron-crontab-root-0.service - [Cron] "0 *        * * *        root        echo dupaninka; false"...
2023-09-10T01:00:00+0200 tarta sh[1743914]: dupaninka
2023-09-10T01:00:00+0200 tarta systemd[1]: cron-crontab-root-0.service: Main process exited, code=exited, status=1/FAILURE
2023-09-10T01:00:00+0200 tarta systemd[1]: cron-crontab-root-0.service: Failed with result 'exit-code'.
2023-09-10T01:00:00+0200 tarta systemd[1]: Failed to start cron-crontab-root-0.service - [Cron] "0 *        * * *        root        echo dupaninka; false".
2023-09-10T01:00:00+0200 tarta systemd[1]: cron-crontab-root-0.service: Triggering OnFailure= dependencies.
```

```
Date: Sun, 10 Sep 2023 00:51:37 +0200
From: systemd-cron <root@tarta.nabijaczleweli.xyz>
To: root@tarta.nabijaczleweli.xyz
Subject: [tarta] /etc/cron.weekly/dnsmasq-update-adblock-hosts: output
X-Mailer: systemd-cron 2.1.1+testupa-1

○ cron-weekly-dnsmasq-update-adblock-hosts.service - [Cron] /etc/cron.weekly/dnsmasq-update-adblock-hosts
     Loaded: loaded (/etc/cron.weekly/dnsmasq-update-adblock-hosts; generated)
     Active: inactive (dead) since Sun 2023-09-10 00:51:36 CEST; 216ms ago
TriggeredBy: ● cron-weekly-dnsmasq-update-adblock-hosts.timer
       Docs: man:systemd-crontab-generator(8)
    Process: 3907001 ExecStart=/etc/cron.weekly/dnsmasq-update-adblock-hosts (code=exited, status=0/SUCCESS)
   Main PID: 3907001 (code=exited, status=0/SUCCESS)
        CPU: 1.068s
2023-09-10T00:51:31+0200 tarta systemd[1]: Starting cron-weekly-dnsmasq-update-adblock-hosts.service - [Cron] /etc/cron.weekly/dnsmasq-update-adblock-hosts...
2023-09-10T00:51:31+0200 tarta dnsmasq-update-adblock-hosts[3907025]: Downloading https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
2023-09-10T00:51:31+0200 tarta dnsmasq-update-adblock-hosts[3907025]: Downloading https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
...
```

```
Date: Sun, 10 Sep 2023 00:51:33 +0200
From: systemd-cron <root@tarta.nabijaczleweli.xyz>
To: nabijaczleweli@tarta.nabijaczleweli.xyz
Subject: [tarta] nabijaczleweli's crontab line 2: output
X-Mailer: systemd-cron 2.1.1+testupa-1

○ cron-nabijaczleweli-nabijaczleweli-0.service - [Cron] "0   *    *   *     *   PATH=$HOME/bin:$HOME/.cargo/bin:$PATH; exec update-feeds ~/.feeds"
     Loaded: loaded (/var/spool/cron/crontabs/nabijaczleweli; generated)
     Active: inactive (dead) since Sun 2023-09-10 00:51:32 CEST; 458ms ago
TriggeredBy: ● cron-nabijaczleweli-nabijaczleweli-0.timer
       Docs: man:systemd-crontab-generator(8)
    Process: 3906894 ExecStart=/bin/sh /run/systemd/generator/cron-nabijaczleweli-nabijaczleweli-0.sh (code=exited, status=0/SUCCESS)
   Main PID: 3906894 (code=exited, status=0/SUCCESS)
        CPU: 6.990s
2023-09-10T00:51:31+0200 tarta systemd[1]: Starting cron-nabijaczleweli-nabijaczleweli-0.service - [Cron] "0   *    *   *     *   PATH=$HOME/bin:$HOME/.cargo/bin:$PATH; exec update-feeds ~/.feeds"...
2023-09-10T00:51:31+0200 tarta sh[3907022]: curl: (6) Could not resolve host: blog.q3w3e3.dev
2023-09-10T00:51:31+0200 tarta sh[3907164]: Reading /run/user/1000/feeds/just-between-us.feed failed: unable to parse feed: no root element
2023-09-10T00:51:31+0200 tarta sh[3907173]: Reading /run/user/1000/feeds/gossip.feed failed: unable to parse feed: no root element
...
```

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
........or just put the line contents themselves, instead of the number, so it's /actually/ useful and meaningful instead of just stupid :v

**Comment by nabijaczleweli** [comment]
```
   2     14:30 systemd-cron    (  14) [tarta] Failure: /etc/crontab "30 *     * * *   root    echo dupaninka; false"
   3   + 14:27 systemd-cron    (  17) [tarta] Output: nabijaczleweli's crontab "0   0    *   *     *   trap 'rm -f "$tmpf"' EXIT; tmpf="$(mktemp)"; /etc/nginx/sit
   4     14:25 systemd-cron    (  31) [tarta] Output: /etc/cron.weekly/dnsmasq-update-adblock-hosts
```

```
Date: Sun, 10 Sep 2023 14:25:35 +0200
From: systemd-cron <root@tarta.nabijaczleweli.xyz>
To: root@tarta.nabijaczleweli.xyz
Subject: [tarta] Output: /etc/cron.weekly/dnsmasq-update-adblock-hosts
X-Mailer: systemd-cron 2.1.1

○ cron-weekly-dnsmasq-update-adblock-hosts.service - [Cron] /etc/cron.weekly/dnsmasq-update-adblock-hosts
     Loaded: loaded (/etc/cron.weekly/dnsmasq-update-adblock-hosts; generated)
    Drop-In: /etc/systemd/system/cron-weekly-dnsmasq-update-adblock-hosts.service.d
             └─override.conf
     Active: inactive (dead) since Sun 2023-09-10 14:25:35 CEST; 63ms ago
TriggeredBy: ● cron-weekly-dnsmasq-update-adblock-hosts.timer
       Docs: man:systemd-crontab-generator(8)
    Process: 306215 ExecStart=/etc/cron.weekly/dnsmasq-update-adblock-hosts (code=exited, status=0/SUCCESS)
   Main PID: 306215 (code=exited, status=0/SUCCESS)
        CPU: 834ms
2023-09-10T14:25:31+0200 tarta systemd[1]: Starting cron-weekly-dnsmasq-update-adblock-hosts.service - [Cron] /etc/cron.weekly/dnsmasq-update-adblock-hosts...
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Dead/hosts
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://adaway.org/hosts.txt
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/tiuxo/hosts/master/ads
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/azet12/KADhosts/master/KADhosts.txt
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext&useip=0.0.0.0
2023-09-10T14:25:31+0200 tarta dnsmasq-update-adblock-hosts[306217]: Downloading https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
2023-09-10T14:25:32+0200 tarta sudo[306290]:     root : PWD=/home/shared-config ; USER=shared-config ; COMMAND=/bin/sh -c 'push-dnsmasq dnsmasq-adblock-update-hosts\\ 2023-09-10T14\\:25\\:32\\+02\\:00'
2023-09-10T14:25:32+0200 tarta sudo[306290]: pam_unix(sudo-i:session): session opened for user shared-config(uid=1011) by (uid=0)
2023-09-10T14:25:33+0200 tarta dnsmasq-update-adblock-hosts[306472]: [trunk e4ee2b0] dnsmasq-adblock-update-hosts 2023-09-10T14:25:32+02:00
2023-09-10T14:25:33+0200 tarta dnsmasq-update-adblock-hosts[306472]:  1 file changed, 48 insertions(+), 2 deletions(-)
2023-09-10T14:25:35+0200 tarta systemd[1]: cron-weekly-dnsmasq-update-adblock-hosts.service: Deactivated successfully.
2023-09-10T14:25:35+0200 tarta systemd[1]: Finished cron-weekly-dnsmasq-update-adblock-hosts.service - [Cron] /etc/cron.weekly/dnsmasq-update-adblock-hosts.
2023-09-10T14:25:35+0200 tarta systemd[1]: cron-weekly-dnsmasq-update-adblock-hosts.service: Triggering OnSuccess= dependencies.
```

```
Date: Sun, 10 Sep 2023 14:27:20 +0200
From: systemd-cron <root@tarta.nabijaczleweli.xyz>
To: nabijaczleweli@tarta.nabijaczleweli.xyz
Subject: [tarta] Output: nabijaczleweli's crontab "0   0    *   *     *   trap 'rm -f "$tmpf"' EXIT; tmpf="$(mktemp)"; /etc/nginx/sites-available/ro.ws.co.ls-manuals.sh | column -t > "$tmpf";  diff -u
        /etc/nginx/sites-available/ro.ws.co.ls-manuals "$tmpf" || { cp "$tmpf" /etc/nginx/sites-available/ro.ws.co.ls-manuals; echo ' '; echo "run systemctl reload nginx"; }; :"
X-Mailer: systemd-cron 2.1.1

--- /etc/nginx/sites-available/ro.ws.co.ls-manuals      2023-09-10 14:26:04.053292069 +0200
+++ /tmp/tmp.0U6kjXvP7O 2023-09-10 14:26:05.605362631 +0200
@@ -1,5 +1,12 @@
 location  =  /                    {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man0/index.0.html;      }
 location  =  /index.0             {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man0/index.0.html;      }
+location  =  /index               {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man0/index.0.html;      }
+location  =  /[.1                 {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/test.1.html;       }
+location  =  /[                   {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/test.1.html;       }
+location  =  /arch.1              {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/uname.1.html;      }
+location  =  /arch                {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/uname.1.html;      }
+location  =  /b2sum.1             {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/sha1sum.1.html;    }
+location  =  /b2sum               {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/sha1sum.1.html;    }
 location  =  /base16.1            {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/basenc.1.html;     }
 location  =  /base16              {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/basenc.1.html;     }
 location  =  /base2lsbf.1         {  return  303  https://srhtcdn.githack.com/~nabijaczleweli/voreutils/blob/man/man1/basenc.1.html;     }

run systemctl reload nginx
```

```
Date: Sun, 10 Sep 2023 14:30:00 +0200
From: systemd-cron <root@tarta.nabijaczleweli.xyz>
To: root@tarta.nabijaczleweli.xyz
Subject: [tarta] Failure: /etc/crontab "30 *     * * *   root    echo dupaninka; false"
X-Mailer: systemd-cron 2.1.1

× cron-crontab-root-0.service - [Cron] "30 *     * * *   root    echo dupaninka; false"
     Loaded: loaded (/etc/crontab; generated)
     Active: failed (Result: exit-code) since Sun 2023-09-10 14:30:00 CEST; 30ms ago
TriggeredBy: ● cron-crontab-root-0.timer
       Docs: man:systemd-crontab-generator(8)
    Process: 318064 ExecStart=/bin/sh /run/systemd/generator/cron-crontab-root-0.sh (code=exited, status=1/FAILURE)
   Main PID: 318064 (code=exited, status=1/FAILURE)
        CPU: 4ms
2023-09-10T14:30:00+0200 tarta systemd[1]: Starting cron-crontab-root-0.service - [Cron] "30 *     * * *   root    echo dupaninka; false"...
2023-09-10T14:30:00+0200 tarta sh[318065]: dupaninka
2023-09-10T14:30:00+0200 tarta systemd[1]: cron-crontab-root-0.service: Main process exited, code=exited, status=1/FAILURE
2023-09-10T14:30:00+0200 tarta systemd[1]: cron-crontab-root-0.service: Failed with result 'exit-code'.
2023-09-10T14:30:00+0200 tarta systemd[1]: Failed to start cron-crontab-root-0.service - [Cron] "30 *     * * *   root    echo dupaninka; false".
2023-09-10T14:30:00+0200 tarta systemd[1]: cron-crontab-root-0.service: Triggering OnFailure= dependencies.
```

**Comment by nabijaczleweli** [comment]
This is much better I think, I dare-say maybe even like it

**Comment by a-detiste** [comment]
>  path is horrific

it's not the biggest problem, users should not do `sudo $EDITOR /var/spool` and should realy use crontab.

so if they don't know where the crontab is it is even better

**Comment by a-detiste** [comment]
> SYSLOG_FACILITY=9

if the use of magic number is a problem a constant can be defined at the top of the script

>src/units/cron-schedule.service.in 
> [Unit]
> Description=systemd-cron @schedule@ script service
> Documentation=man:systemd.cron(7)
> PartOf=cron-@schedule@.target
> ConditionDirectoryNotEmpty=/etc/cron.@schedule@
> OnFailure=cron-mail@cron\x2d@schedule@.service

does this old OnFailure syntax is still supported by the new mail_for_job ?

OnSuccess for the run-parts mode looks like a plain bad idea...
it's just the random garbage output of unrelated scripts cobbled togheter,
this mode is still suported but deprecated

**Comment by a-detiste** [comment]
> "0   *    *   *     *   

The old python version was compressing the extraneous whitespaces

**Comment by nabijaczleweli** [comment]
I don't think cron=9 it's an issue really, we document it and it's in a `SYSLOG_FACILITY=` prefix, so meh. Pulling it out is more confusing.

Yes, `mail_for_job` should work with the old syntax (in the default config – with metadata and without nonempty checks). Since this is just OnFailure=, the run-partsed jobs will never send mail on success (which matches the pre-2.1 behaviour.

I remove space squeezing since it damaged the line, and now it makes it so related cronjobs are aligned like they are in the source in systemctl:
image
which makes it much more readable
(it also makes memory management easier).

**Comment by a-detiste** [comment]
alright !

**Comment by a-detiste** [comment]
maybe a `sed` filter to clean $description in mail_for_job.sh ?

this really as the lowest of importance

https://stackoverflow.com/questions/23402740/how-to-remove-duplicated-characters-from-string-in-bash

you can edit the Changelog too to your taste

**Comment by a-detiste** [comment]
```
sed 's/ */ /g'
```

**Comment by nabijaczleweli** [comment]
that's better-spelled `tr -s ' '` and I think I prefer it spaced as in the source, instead of breaking it.

doesn't really matter if you get like one cron mail, but if you imagine you have stuff like
```
  0   *    *   *     *   PATH=$HOME/bin:$HOME/.cargo/bin:$PATH; exec update-feeds ~/.feeds
 10  23    *   *     *   PATH=$HOME/bin:$HOME/.cargo/bin:$PATH; exec update-feeds ~/.feeds
```
then this would get turned into
```
 0 * * * * PATH=$HOME/bin:$HOME/.cargo/bin:$PATH; exec update-feeds ~/.feeds
 10 23 * * * PATH=$HOME/bin:$HOME/.cargo/bin:$PATH; exec update-feeds ~/.feeds
```
which kinda sucks

**Comment by a-detiste** [comment]
OK I didn't thought of text-based mail programs

**Pull request merged**
