### PR TITLE
demo

### PR DESCRIPTION
**Pull request by a-detiste**
the code is horribly botched. I acknoweldge.

but the goal is nice ?

image

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
eeeeeh. is there much point to this? `crontab -t` is for translating a line  into a systemd unit pair, and this.... muddles that somewhat for what I don't think is a great reason. if the user really cares about "when this cron jobspec will next elapse" it's just a copy-paste into sd-analyze away, and the systemd calendar format is quite sane and easy to understand as-is, so there's little point in injecting a huge blob with not that much info in it (and also with incorrect buffering and the wrong timezone).

do you find yourself wanting to translate a job *and* do calendar analysis often, in the same step? maybe this could be a separate crontab flag (that runs s-c-g --translate, extracts OnCalendar= from the output, and execs systemd-analyze)? so you could do, say 
```
$ crontab() { command crontab -t "$2 :" | grep -m1 OnCalendar= | { IFS== read -r _ cal; echo "$2:"; exec systemd-analyze calendar "$cal"; }; }
$ crontab -c '01 * * * *'
01 * * * *:
  Original form: *-*-* *:1:00
Normalized form: *-*-* *:01:00
    Next elapse: Thu 2023-09-14 01:01:00 CEST
       (in UTC): Wed 2023-09-13 23:01:00 UTC
       From now: 3min 19s left
```
wh

**Comment by a-detiste** [comment]
systemd-analyze does validate & "normalize" the calendar spec.

the next run is just eye candy

**Comment by a-detiste** [comment]
systemd-analyze's stdout could be silenced to only keep the double-parsing+stderr.

**Comment by a-detiste** [comment]
`SYSTEMD_UNIT_PATH=/lib/systemd/system:/tmp/x systemd-analyze verify x.service`
might be more usefull, here it find the mistyped program name that `--test` did not complained about ( #91 )

image

**Comment by nabijaczleweli** [comment]
Yeah, this is sensible, I think have a nice design that will (a) move the grody formatting/forking bits out of the generator and (b) make doing these checks (#126, the time one from here, whatever) easy. But this will have to wait until I'm not asleep.

**Comment by nabijaczleweli** [comment]
but here's a draft

**Comment by nabijaczleweli** [comment]
Actually nevermind, you're a bad influence; #127

**Pull request closed without merging**
