### PR TITLE
cron-update.service cleanups

### PR DESCRIPTION
**Pull request by nabijaczleweli**
See commit messages for details

### CODE REVIEW

**Comment by a-detiste** [comment]
On some systems, original cron will wait up to one whole minute to read new crontabs...
I think that 1 second is tollerable.
I remember having systemd crashing horribly with too much daemon-reload abuse, but it  was many years ago, but still don't want to open up again this old can of worm. (which means: reading for hours old bug reports that leaded to the `sleep 1`)

**Comment by nabijaczleweli** [comment]
There appear to not be any:
```diff
$ git show 85518c14
commit 85518c14c38f58986257d1c69bc148361324a649
Author: Alexandre Detiste <alexandre.detiste@gmail.com>
Date:   Mon Nov 3 13:12:46 2014 +0100

    make cron-update race-proof

diff --git a/src/units/cron-update.service.in b/src/units/cron-update.service.in
index 9f5ac4a..f23fe92 100644
--- a/src/units/cron-update.service.in
+++ b/src/units/cron-update.service.in
@@ -5,5 +5,4 @@ Documentation=man:systemd.cron(7)
 [Service]
 Type=oneshot
 ExecStartPre=/usr/bin/touch /run/crond.reboot
-ExecStart=/bin/systemctl daemon-reload
-ExecStartPost=/bin/systemctl try-restart cron.target
+ExecStart=/bin/sh -c '/bin/systemctl daemon-reload ; sleep 1 ; /bin/systemctl try-restart cron.target'
```

It appears to have gone straight from "let's schedule this as three different jobs" to "reload; sleep; restart".

By looking through bugs on here and by requesting all historical sd-cron debbugs (sorry DSA and buxtehude in particular), I found the reason for merging these to likely be https://bugs.debian.org/856985, which crashed systemd when they were three different jobs.

I imagine the thought process being "we need to run them in the same job. hm daemon-reload may take some time! okay so let's just add a sleep 1". Which is reasonable, if (a) daemon-reload didn't just wait until the reload was done (maybe it didn't in jessie yet!) and (b) reloads didn't take >1s.

It works on my system, and it *ought to* work in general – daemon-reload waits until the reload is done. This is something I'd like to try, at least – all artificial delay is unacceptable IMO – and we can easily revert it if it turns out it breaks.

**Comment by a-detiste** [comment]
I ve had so many crashes !
I rember having to phone someone to power-cycle the machine in question
(an humber Raspberry Pi)

`workaround_var_not_mounted()` is an other horror that is there to stay,
but at least it's contained

**Comment by a-detiste** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776859 trauma

**Pull request merged**
