### PR TITLE
Last (week-)day of month

### PR DESCRIPTION
**Pull request by a-detiste**
(the cron syntax is here more understable than the systemd one)

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Even barring the obvious implementation, uh... questionables, this doesn't appear to have any basis in any other implementation (incl. cronie)? Again, I don't want to Just Invent Random Stuff that has no real-world use (clearly, since no-one implements this) and is of limited usefulness (the parsing's bad enough as-is) and potential conflict with other, standard, future expansion.

**Comment by nabijaczleweli** [comment]
I don't see how this maps to the systemd concept at all, anyway – in cron parlance you'd want to be able to say `0 0 1,7,14,21,L * * program` but AFAICT under systemd this would map to at *least* two OnCalendar= stanzas? What would `0 0 1,7,14,21,L * Mon program` mean? What would `0 0 1,7,14,21,L * L program` mean? How would you express it in systemd OnCalendar=?

**Comment by a-detiste** [comment]
> any basis in any other implementation

I ve seen in intro proprietary products used to cobble togheter an ETL/BI pipeline (I want to forget this).

These proprietary extensions did leaked up here:
https://en.wikipedia.org/wiki/Cron#Cron_expression


It's a quite common request, I saw it popping up while review this project (and cron & cronie) history and bug repports:

https://www.phoronix.com/forums/forum/software/general-linux-open-source/34137-systemd-dreams-up-new-feature-makes-it-like-cron/page12?fbclid=IwAR36aAV-_IH3RAkIYVCYtdODZ8gyFFeRpE2JyxOkJ0jP-M5zOXx-9GXYJnk#post405513

In the weird Debian's cron alternate universe that splitted of in 1993 they did patched the man page to provide a recipe to get to a similar result,
https://sources.debian.org/src/cron/3.0pl1-175/debian/patches/fixes/Manpage-corrections-and-improvements.patch/#L464
(it works, but with a lot of useless wakeups & logging).

We even carry a fork of this manpage still... (I should also include a review of it in the PR)
I prefer to write good code than bad documentation.


In systemd they provide something similar but the syntax is quite obscure 
https://www.freedesktop.org/software/systemd/man/systemd.time.html
> ... "Mon *-05~07/1" means "the last Monday in May."

And the tilde means someting else in crontabs.

So systemd-cron's job is to make people life easier, they may want to use this systemd feature
without translating the whole crontab to .timer + .service

Or they may want to use the `--translate` feature to get a headway.

> What would 0 0 1,7,14,21,L * L program mean

Nothing, it would be rejected.

Only accepting [0-7]L for day of week and 'L' for day of month.

**Comment by a-detiste** [comment]
if the '~1' trick was not in systemd I would never had bothered

https://backreference.org/2010/04/05/last-day-of-month-cron-job/index.html

**Comment by a-detiste** [comment]
AutoSYS is one such 'Enterprise Scheduler', it's really a hard to find any public information

https://techdocs.broadcom.com/us/en/ca-enterprise-software/intelligent-automation/autosys-workload-automation/12-0/reference/ae-commands/define-workload-objects/cron2jil-command-convert-unix-crontab-data-to-a-jil-script-or-calendar-file.html

BroadCom has bought CA Technologies and is build up a portfolio of zombie proprietary software with 0 development but it's only about billing yearly licensing fees.

**Comment by a-detiste** [comment]
And then it really feels like scrapping the bottom of the barrel with this project and then considerign it done/in maintenance mode.
Cheers

**Comment by nabijaczleweli** [comment]
Real wordsmithery in the linked manual lmfao
```
0 4 * * Sat   [ "$(date +\e%e)" = "$(LANG=C ncal | sed \-n 's/^Sa .* \e([0\-9]\e+\e) *$/\e1/p')" ] && echo "Last Saturday" && program_to_run
```

I think it'd only make sense to provide this if it, well, behaves like everything else in a crontab *and* like it does in other implementations.

Computing Wikipedia is hardly a source, but even it says
> The following are non-standard characters and exist only in some cron implementations, such as the [Quartz Java scheduler](https://en.wikipedia.org/wiki/Quartz_(scheduler)).
> 
> L
>     'L' stands for "last". When used in the day-of-week field, it allows specifying constructs such as "the last Friday" ("5L") of a given month. In the day-of-month field, it specifies the last day of the month.

The... "Quartz Java scheduler" isn't a cron implementation. It sure looks like it's just a library that parses "something that looks vaguely like crontabs" but isn't. I still haven't seen evidence of *cron implementations* implementing this.
Wikipedia is full of stuff like this.

Do I think it would be nice to be able to say `day=1,8,15,22,L`? or something to that effect? Yes. But only *if* it Just Behaves Like A Cron Jobspec, and is `1,8,15,22,28`/`1,8,15,22,29`/`1,8,15,22,30`/`0,7,14,21,31`.

I think if systemd *did* support something like this, then that'd be great, and we could be the pioneering implementation. But I don't think it does, and I don't think its support for the weirdo syntax is reason enough to saddle ourselves with something that Is Kinda Weird and Needs To Be Compatible Forever. Yet. 

The ~ feature is cool! But it appears insufficient at this time. Maybe this could be revisited in a few years when systemd grows something more responsible (because, as it stands, our implementation would be copying directly all the features and bugs of the systemd implementation, *and* all of the minutiae we haven't yet thought about or noticed. which. not great).

Or another implementation implements this and we have a concrete baseline to target, and can mould whatever systemd does to match what users expect.

I would love to have this feature *if it were correct and I could rely on it to stay consistent or to Just Work Cronly*. But the façade of "hey we can generate OnCalendar= that looks kinda similar" is not strong enough in this case, and it'll just be another thing that's hard to document, use, and keep maintaining, especially with no consensus.

As it stands, I think the "ecosystem" is not mature enough to burden ourselves with this. Does this make sense?

**Comment by nabijaczleweli** [comment]
But yes I agree, once all the subtle bugs are fixed I would love to put this in "i get a bug twice a year and fix it in 30 minutes" mode, which is why I'd personally prefer a smaller set (and it's not even that small now! I'd call it "fully-featured"!) of consistent features than pioneering experimental features with no user/implementation consensus or wide user-base that would provide fast feedback in our case. (This is something that fedora cron has that we don't, and I consider this crucial to turning "hm i have a draft feature that idk if it behaves like users expect" into a definitive yes or no.)

And even AutoSYS says
> Because the cron2jil command cannot comprehensively address all job processing requirements, you should use it as a first step in converting from cron to the environment. The second step requires editing the newly created JIL and calendar files to ensure the preferred job processing.

**Comment by a-detiste** [comment]
I just want this out of my mind, so it can rest here in this PR for a long time. And it's quite a tiny change codewise.
(because it merely preprocess the dows variable without extensive refactoring)

Here I see that these new 100 people prefer 'your' systemd-cron over 'mine', but I'm perfectly happy with that:
https://qa.debian.org/popcon.php?package=systemd-cron it's been holding of for almost 10 years.

Next step for mini is the MiniDebConf in Cambridge in November when I'll have the talk 'we should switch to cronie now ... or else ?' but not much else to do inbetween.

**Comment by a-detiste** [comment]
I think because it's such a pain to create `systemctl --user` jobs (the "lingering" thing" ...), systemd-cron might stick around forever

**Comment by a-detiste** [comment]
>  smaller set 

a lot of tiny things were dropped in 2.0 (configure options...)

**Comment by a-detiste** [comment]
> The ~ feature is cool! But it appears insufficient at this time. Maybe this could be revisited in a few years when systemd grows something more responsible

This needs a talk face to face with people managing hundred of VM's.

I manage hundred of tramways & buses ... the human provides the randomisation for me (when they turn the key ...)

**Comment by a-detiste** [comment]
In a previous life I was the one snitching the people with a new cable TV subscription to the state agency.
Every last Mondy of the month.

> 1,8,15,22,L

no, users will have to define two crontab lines:  1,8,15,22   &   "L"

**Comment by a-detiste** [comment]
> fedora cron

We'd need this to for Fedora ...  I don' know what the last line does

It could be an experiment.

https://github.com/cronie-crond/crontabs/blob/master/run-parts#L48

```
	# Don't run *.{rpmsave,rpmorig,rpmnew,swp,cfsaved} scripts
	[ "${i%.cfsaved}" != "${i}" ] && continue
	[ "${i%.rpmsave}" != "${i}" ] && continue
        [ "${i%.rpmorig}" != "${i}" ] && continue
        [ "${i%.rpmnew}" != "${i}" ] && continue
        [ "${i%.swp}" != "${i}" ] && continue
	[ "${i%,v}" != "${i}" ] && continue
```

I don't undestand what last line does.

**Comment by nabijaczleweli** [comment]
On Sat, Sep 30, 2023 at 07:24:24AM -0700, Alexandre Detiste wrote:
> 	[ "${i%.cfsaved}" != "${i}" ] && continue
> 	[ "${i%.rpmsave}" != "${i}" ] && continue
>         [ "${i%.rpmorig}" != "${i}" ] && continue
>         [ "${i%.rpmnew}" != "${i}" ] && continue
>         [ "${i%.swp}" != "${i}" ] && continue
> 	[ "${i%,v}" != "${i}" ] && continue
this skips files whose names end in
  .cfsaved
  .rpmsave
  .rpmorig,
  .rpmnew
  .swp
  ,v
("if i with .cfsaved removed from the end is different from i"
 <=> "if i ends with .cfsaved").

I think debian run-parts does something similar (but with .dpkg-*).
.swp (and .swo) is what vi uses.
,v is used by CVS and SCCS I think?

**Comment by a-detiste** [comment]
> ,v is used by CVS and SCCS I think?

So this is lost in time.

Debian run-parts is more restrictive/annoying and I think it forbids all files with a dot.

`Debian cron script namespace (^[a-zA-Z0-9_-]+$)`

It's really annoying because you job is silently ignore and you have to find out the hard way.

**Comment by a-detiste** [comment]
I think Debian is wrong. Or the rule should only apply to package-provided cron job, not admin-defined one.

https://blog.ndk.name/top-5-reasons-your-crontab-scripts-are-not-working/ : more random online blogs to paper over this bad taste

**Comment by hifron** [comment]
There are system jobs and user jobs. And if cron last development was in 1993 and in future Ubuntu its(cron) config options are mostly dropped, maybe Fedora's cronie would replace cron generated with system or user systemd services like in `systemctl list-timers` but should be edited user friendly way and if there are a lot of applications using this cron or anacron, then it should be make compatible...

On next Ubuntu Noble [changelogs](https://changelogs.ubuntu.com/changelogs/pool/universe/s/systemd-cron/systemd-cron_2.3.0-2/changelog) says that systemd-cron now attempts
    to have feature parity with cron & cronie and do not 'Replaces: cron', it is not needed anymore
    since the cron-daemon-common split.

Maybe apps needs to be make compatible... but crontab -e is still on demand including user jobs.

**Comment by a-detiste** [comment]
@hifron : I'm still trying to make sense of what you said.

For the record, what's in Ubuntu is what I uploaded in Debian before so I know these lines of text...

`crontab -e` just works.

**Pull request merged**
