### PR TITLE
colorize

### PR DESCRIPTION
**Pull request by a-detiste**
I'm so bad at it !

Never used template. (only some 'vector' and 'pair')

Will look again later

```g++ -O2 -Wall -Wextra -fno-exceptions -Wno-psabi  -std=c++20 -I /home/tchet/git/systemd-cron/out/build/include  /home/tchet/git/systemd-cron/src/bin/crontab.cpp -o /home/tchet/git/systemd-cron/out/build/bin/crontab 
/home/tchet/git/systemd-cron/src/bin/crontab.cpp: In function ‘int read(const char*, const char*, {anonymous}::autodeleting_path, FILE*)’:
/home/tchet/git/systemd-cron/src/bin/crontab.cpp:177:49: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘FILE*’ in assignment
  177 |         if(tmp_fd == -1 || !(tmp = {tmp_fd, "w+"}))
      |                                                 ^
make: *** [Makefile:226 : /home/tchet/git/systemd-cron/out/build/bin/crontab] Erreur 1
```

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Unclear to me what this is supposed to be doing. `edit()` is special since it wants a named file, and it has strict lifetime requirements (which this, again, breaks). Overgenerality for no reason is harmful, more-so than it is worth (and this clearly holds in this case).

Considering `list()` is
```cpp
static auto list(const char * cron_file, const char * user) -> int {
	if(vore::file::FILE<false> f{cron_file, "r"}) {
		copy_FILE(f, stdout);
		check(cron_file);
		try_chmod(cron_file, user);
		return 0;
	}
	auto err = errno;

	if(err == ENOENT)
		return std::fprintf(stderr, "no crontab for %s\n", user), ENOENT;

	if(user != current_user)
		return std::fprintf(stderr, "you can not display %s's crontab\n", user), 1;

	if(HAVE_SETGID)
		return exec(SETGID_HELPER, "r");

	return std::fprintf(stderr, "%s\n", std::strerror(err)), 1;
}
```
and you want to add colour to it when colour is enabled, you can very literally do
```diff
diff --git a/src/bin/crontab.cpp b/src/bin/crontab.cpp
index fca33b9..6e4093e 100644
--- a/src/bin/crontab.cpp
+++ b/src/bin/crontab.cpp
@@ -77,12 +77,14 @@ static auto run_generator(const char * op, const char * file_or_line, bool file_
 }
 
 static const bool want_colour = !*(std::getenv("NO_COLOR") ?: "") && (std::getenv("TERM") ?: ""sv).find("color"sv) != std::string_view::npos && isatty(1);
+#define COLOUR_BLUE "\033[1;34m"
+#define COLOUR_RESET "\033[0m"
 static void blue(const char * line) {
 	if(want_colour)
-		std::fputs("\033[1;34m", stdout);
+		std::fputs(COLOUR_BLUE, stdout);
 	std::fputs(line, stdout);
 	if(want_colour)
-		std::fputs("\033[0m", stdout);
+		std::fputs(COLOUR_RESET, stdout);
 }
 
 static auto translate(const char * line) -> int {
@@ -156,9 +158,31 @@ static auto try_chmod(const char * cron_file = nullptr, const char * user = null
 				(void)chmod(cron_file, 00600);  // rw-------
 }
 
+static auto colour_crontab(FILE * f) -> void {
+	char * line_raw{};
+	std::size_t linecap{};
+	for(ssize_t len; (len = getline(&line_raw, &linecap, f)) != -1;) {
+		std::string_view line{line_raw, static_cast<std::size_t>(len)};
+
+		const char * colour{};
+		if(line[0] == '#')
+			colour = COLOUR_BLUE;
+		// other matchers
+
+		if(colour)
+			std::fputs(colour, stdout);
+		std::fwrite(line.data(), 1, line.size(), stdout);
+		if(colour)
+			std::fputs(COLOUR_RESET, stdout);
+	}
+}
+
 static auto list(const char * cron_file, const char * user) -> int {
 	if(vore::file::FILE<false> f{cron_file, "r"}) {
-		copy_FILE(f, stdout);
+		if(!want_colour)
+			copy_FILE(f, stdout);
+		else
+			colour_crontab(f);
 		check(cron_file);
 		try_chmod(cron_file, user);
 		return 0;
@@ -171,8 +195,32 @@ static auto list(const char * cron_file, const char * user) -> int {
 	if(user != current_user)
 		return std::fprintf(stderr, "you can not display %s's crontab\n", user), 1;
 
-	if(HAVE_SETGID)
-		return exec(SETGID_HELPER, "r");
+	if(HAVE_SETGID) {
+		if(!want_colour)
+			return exec(SETGID_HELPER, "r");
+
+		int pipe[2];
+		pipe2(pipe, O_CLOEXEC);
+		switch(pid_t child = vfork()) {
+			case -1:
+				return std::fprintf(stderr, "%s: couldn't create child: %s\n", self, std::strerror(errno)), 125;
+			case 0:  // child
+				dup2(pipe[1], 1);
+				_exit(exec(SETGID_HELPER, "r"));
+			default: {  // parent
+				close(pipe[1]);
+				vore::file::FILE<false> f{pipe[0], "r"};
+				if(!f)
+					return std::fprintf(stderr, "%s\n", std::strerror(err)), 1;
+				colour_crontab(f);
+
+				int childret;
+				while(waitpid(child, &childret, 0) == -1 && errno == EINTR)  // no other errors possible
+					;
+				return WIFSIGNALED(childret) ? 128 + WTERMSIG(childret) : WEXITSTATUS(childret);
+			}
+		}
+	}
 
 	return std::fprintf(stderr, "%s\n", std::strerror(err)), 1;
 }
```
which yields

and have a field day with the matchers to rice it out however you like.

**Comment by a-detiste** [comment]
> Overgenerality for no reason is harmful

You have more experience. I know the "Dont Repeat Yourself" from elsewhere and I don't know where to apply it.

> and have a field day with the matchers to rice it out however you like.

That's the plan.

The could you wrote is "cronie parity" but I want to got a tiny little further.

**Comment by a-detiste** [comment]
The more meta goal is to become better at C++

**Comment by nabijaczleweli** [comment]
for once i agree with the tef take on DRY: https://programmingisterrible.com/post/176657481103/repeat-yourself-do-more-than-one-thing-and

Feel free to just copy the diff (`patch -p1` off the github comment may even work! or https://github.com/nabijaczleweli/systemd-cron/commit/d18e45c5ecfaf6f4077346e2e909aff2af78c7db) and add the rules you want, of course.

And god help you in your C++ enthusiasm, reading through the entire n4140 standard in middle school probably did irreparable damage to my brain

**Pull request closed without merging**
